### ISSUE TITLE
Sometimes presser count does not go down

### ISSUE THREAD

**Issue by zwalsh-toast** [zwalsh/button#2]
Probably related to the `@Synchronized` update function, maybe this stack trace:
```
May 03 14:23:44 vultr.guest button[30569]: Exception in thread "pool-1-thread-4" java.util.ConcurrentModificationException
May 03 14:23:44 vultr.guest button[30569]:         at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
May 03 14:23:44 vultr.guest button[30569]:         at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742)
May 03 14:23:44 vultr.guest button[30569]:         at sh.zachwal.button.presser.PresserManager.update(PresserManager.kt:44)
May 03 14:23:44 vultr.guest button[30569]:         at sh.zachwal.button.presser.PresserManager.pressed(PresserManager.kt:23)
May 03 14:23:44 vultr.guest button[30569]:         at sh.zachwal.button.presser.Presser.handleIncomingText(Presser.kt:65)
May 03 14:23:44 vultr.guest button[30569]:         at sh.zachwal.button.presser.Presser.handleIncomingFrame(Presser.kt:52)
May 03 14:23:44 vultr.guest button[30569]:         at sh.zachwal.button.presser.Presser.access$handleIncomingFrame(Presser.kt:20)
May 03 14:23:44 vultr.guest button[30569]:         at sh.zachwal.button.presser.Presser$watchChannels$incoming$1.invokeSuspend(Presser.kt:36)
May 03 14:23:44 vultr.guest button[30569]:         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
May 03 14:23:44 vultr.guest button[30569]:         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
May 03 14:23:44 vultr.guest button[30569]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
May 03 14:23:44 vultr.guest button[30569]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
May 03 14:23:44 vultr.guest button[30569]:         at java.lang.Thread.run(Thread.java:748)
```

**Comment by samuelkyl** [comment]
Does this only happen once in a while? I can take it

**Comment by suzannebecker-toast** [comment]
> Does this only happen once in a while? I can take it

It happens like every single day

**Comment by sleungtoast** [comment]
but not every single click

**Comment by samuelkyl** [comment]
but not every single click right?

**Comment by suzannebecker-toast** [comment]
> but not every single click right?

about half the time when I am demoing it to a new party, the count gets stuck at 1 instead of 0. Not every click, but maybe once every 10-30 presses.
